// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unique.Shoes.MarketAPI.Model.Database;

#nullable disable

namespace Unique.Shoes.MarketAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250108232804_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unique.Shoes.Middleware.Database.DBO.ShopItemsTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("count")
                        .HasColumnType("boolean");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("flags")
                        .HasColumnType("text[]");

                    b.Property<string>("hashName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imageLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<string[]>("sizes")
                        .HasColumnType("text[]");

                    b.HasKey("id");

                    b.ToTable("shopItemsTableObj");

                    b.HasData(
                        new
                        {
                            id = 1,
                            count = true,
                            description = "Nike Air Jordan 1 Retro Low OG SP Travis Scott Olive (W) — это уникальная версия классической модели кроссовок Air Jordan 1, созданная в сотрудничестве с популярным рэпером Трэвисом Скоттом.",
                            flags = new[] { "new" },
                            hashName = "e694bbbcd87f95e8a052f7369ac49304",
                            imageLink = "../",
                            name = "Nike Air Jordan 1 Retro Low OG SP Travis Scott Olive (W)",
                            price = 79990,
                            sizes = new[] { "36 RU", "41 RU" }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
