// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unique.Shoes.PaymentAPI.Model.Database;

#nullable disable

namespace Unique.Shoes.PaymentAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unique.Shoes.Middleware.Database.DBO.BankCardTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("moneyValue")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("bankCardTableObj");

                    b.HasData(
                        new
                        {
                            id = 1,
                            cardNumber = "0000 1234 0000 4321",
                            cvv = "123",
                            moneyValue = 10000000
                        });
                });

            modelBuilder.Entity("Unique.Shoes.Middleware.Database.DBO.PayTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cardNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hashPay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("payStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("payTableObj");
                });
#pragma warning restore 612, 618
        }
    }
}
